### ISSUE TITLE
Wordpress connect or login API for Android

### ISSUE THREAD

**Issue by vipulyaara** [Automattic/wpcom-connect-examples#4]
Hi,

I am building an Android app where users can log into their Wordpress account. I am unable to find a login API for this purpose. Does this work with Android apps?

**Comment by aduth** [comment]
Hi @vipulyaara ! The [WordPress.com Developer Site](https://developer.wordpress.com/) is your best bet for the latest documentation. To your specific question about authorizing users using their WordPress.com account, you'll want to review the information about OAuth2 or WordPress.com Connect:

- https://developer.wordpress.com/docs/oauth2/
- https://developer.wordpress.com/docs/wpcc/

The OAuth flow requires a web context. For Android apps, you may be able to use something like a [WebView](https://developer.android.com/reference/android/webkit/WebView.html) to navigate the user through the OAuth flow. Once you've received an access token for the user, you can use it from native code by including it with requests to the WordPress.com REST API ([authentication docs](https://developer.wordpress.com/docs/oauth2/), [API endpoint docs](https://developer.wordpress.com/docs/api/)).

**Comment by vipulyaara** [comment]
Thank you so much. It helped.
